import type { Locale } from '../i18n/ui';

export const runtime = {
  en: {
    meta: { title: 'The Organizational Runtime — Diskarte', description: 'What the Organizational Runtime is: constitutional governance, memory, judgment, and delegation around interchangeable AI execution — and who owns which truth.' },
    hero: {
      eyebrow: 'Runtime',
      h1: 'The runtime around the agents',
      lede: 'Diskarte is a constitutional operating environment in which an organization’s commitments, work, and knowledge are governed — and through which it can safely delegate increasing autonomy to AI.',
      sub: 'Agents and models operate inside it. The product is everything around them: organizational context, authority, memory, judgment, governance, delegation, and execution.',
    },
    anatomy: {
      eyebrow: 'Anatomy',
      h2: 'One seam in, one owner per truth',
      lede: 'Every surface speaks to the Runtime through a single Platform API. Nothing reaches the kernel, storage, or cognition directly.',
      parts: [
        { nm: 'Desktop — custody', ds: 'The native host. It owns exactly one truth: what is on this disk. It runs the claim ceremony, holds credentials in the keychain, and composes pinned runtime and UI artifacts — failing closed on mismatch.', kind: 'impl' },
        { nm: 'Platform API — the seam', ds: 'The single entrance, contract-typed at every boundary. It holds no governance logic of its own.', kind: 'impl' },
        { nm: 'Kernel — authority', ds: 'Seven primitives. Authority is computed as Role ∩ Boundary at the moment of authorization, never stored. It governs; it never reasons.', kind: 'impl' },
        { nm: 'Governance — the one door', ds: 'Intake → Proposal → adjudication → promotion. Machine advice and human intent enter through the same door and are judged by the same pipeline. Batch-accept does not exist.', kind: 'impl' },
        { nm: 'Memory — two planes', ds: 'Canonical memory is the system of record; retrieval memory is derived acceleration, rebuildable at any time. Collapsing them is prohibited.', kind: 'impl' },
        { nm: 'Judgment — rulings', ds: 'Deterministic standings over candidate beliefs, with confidence-inflation and circular-evidence defenses. Humans rule; the interface never pre-selects.', kind: 'impl' },
        { nm: 'Cognition — the interior', ds: 'Produce and Judge behind one port. Structurally barred — by import guards, not policy — from storage, authority, identity, and lifecycle.', kind: 'impl' },
        { nm: 'Substrate — where FLOPs run', ds: 'Abstract requirements, governed bindings, five deployment profiles. Model identity travels only as provenance on produced work.', kind: 'impl' },
        { nm: 'Operations Platform — outside', ds: 'How Diskarte-the-company provisions, releases, and operates deployments. Structurally incapable of holding authority inside any organization.', kind: 'depl' },
      ],
    },
    ownership: {
      eyebrow: 'Boundaries',
      h2: 'Every truth has exactly one owner',
      lede: 'What a layer cannot enforce, it may only reflect — visibly labeled as a reflection.',
      rows: [
        ['Kernel', 'authority decisions, invariants', 'reasoning, substrate names'],
        ['Runtime governance', 'canon, membership, policies, bindings', 'anything a model asserted but no human ratified'],
        ['Cognition', 'proposals, evaluations, learning', 'authority, canon writes, credentials'],
        ['Desktop', 'custody — what is on this disk', 'server truths; it reflects them, labeled'],
        ['Operations Platform', 'setup codes, installations, releases, appliances', 'constitutional authority in any organization'],
        ['Identity provider', 'the external identity itself', 'any decision about what it may do'],
        ['Substrate layer', 'providers, resources, health', 'knowledge — a provider swap never mutates a Practice'],
        ['Nobody', '“ceremony complete”, “ready to execute” — derived by asking each plane', 'a stored composite; there is no orchestrator of record'],
      ],
      cols: ['Layer', 'Owns', 'Must never absorb'],
    },
    provenance: {
      eyebrow: 'Execution',
      h2: 'Accountable execution',
      lede: 'Every machine-produced artifact durably records what produced it and what judged it — model, provider kind, resource, grounding — as evidence attached to the work, never as a gate. Requests address capabilities, never models; the schema refuses vendor names inside the constitution.',
      link: 'Go deeper: the Architecture page',
    },
    cta: { title: 'Build with us.', body: 'Apply to become a design partner and help shape the runtime against real organizational needs.' },
  },
  ja: {
    meta: { title: '組織のためのランタイム — Diskarte', description: '組織ランタイムとは何か：交換可能なAI実行レイヤーを取り囲む、憲法的ガバナンス・記憶・判断・委任 — そして「どの真実を誰が所有するか」。' },
    hero: {
      eyebrow: 'ランタイム',
      h1: 'エージェントを取り囲むランタイム',
      lede: 'Diskarteは、組織のコミットメント・仕事・知識が統治される「憲法的な実行環境」です。これを通じて、組織はAIへの自律的な委任を安全に拡大できます。',
      sub: 'エージェントやモデルはその中で動作します。プロダクトはその周囲のすべて — 組織の文脈、権限、記憶、判断、ガバナンス、委任、実行です。',
    },
    anatomy: {
      eyebrow: '解剖図',
      h2: '入口はひとつ、真実の所有者もひとつ',
      lede: 'すべてのサーフェスは、単一のプラットフォームAPIを通じてランタイムと対話します。カーネル・ストレージ・認知に直接触れるものはありません。',
      parts: [
        { nm: 'デスクトップ — カストディ', ds: 'ネイティブホスト。所有する真実はただひとつ、「このディスクに何があるか」。クレーム・セレモニーを実行し、資格情報をキーチェーンに保持し、ピン留めされたアーティファクトを合成します。不一致時はフェイルクローズ。', kind: 'impl' },
        { nm: 'プラットフォームAPI — シーム', ds: '唯一の入口。すべての境界で契約により型付けされ、それ自体はガバナンスのロジックを持ちません。', kind: 'impl' },
        { nm: 'カーネル — 権限', ds: '7つのプリミティブ。権限は認可の瞬間に Role ∩ Boundary として計算され、保存されません。統治はしますが、推論はしません。', kind: 'impl' },
        { nm: 'ガバナンス — 唯一の扉', ds: 'インテイク → プロポーザル → 裁定 → 昇格。機械の助言も人間の意図も同じ扉から入り、同じパイプラインで判断されます。「一括承認」は存在しません。', kind: 'impl' },
        { nm: '記憶 — 2つのプレーン', ds: 'カノン記憶は正式な記録。検索記憶は派生した高速化レイヤーで、いつでも再構築可能。両者の混同は禁止されています。', kind: 'impl' },
        { nm: '判断 — ルーリング', ds: '候補の信念に対する決定論的なスタンディング。確信度インフレと循環エビデンスへの防御つき。裁くのは人間で、UIは決して先に選びません。', kind: 'impl' },
        { nm: '認知 — インテリア', ds: 'Produce / Judge のひとつのポートの背後に。ストレージ・権限・アイデンティティ・ライフサイクルから、ポリシーではなくインポートガードによって構造的に遮断。', kind: 'impl' },
        { nm: 'サブストレート — 計算の場所', ds: '抽象的な要件、統治されたバインディング、5つのデプロイプロファイル。モデルの識別子は生成物の来歴としてのみ移動します。', kind: 'impl' },
        { nm: 'オペレーション基盤 — 外側', ds: 'Diskarte社がデプロイをプロビジョニング・リリース・運用する仕組み。どの組織の内部でも権限を持てないよう、構造的に設計されています。', kind: 'depl' },
      ],
    },
    ownership: {
      eyebrow: '境界',
      h2: 'あらゆる真実に、所有者はちょうど一人',
      lede: '強制できない真実は、映すことしかできません — しかも「反映である」と明示して。',
      rows: [
        ['カーネル', '権限の決定、不変条件', '推論、サブストレートの名前'],
        ['ランタイム・ガバナンス', 'カノン、メンバーシップ、ポリシー、バインディング', '人間が承認していないモデルの主張すべて'],
        ['認知', '提案、評価、学習', '権限、カノンへの書込み、資格情報'],
        ['デスクトップ', 'カストディ — このディスクにあるもの', 'サーバー側の真実（明示して映すのみ）'],
        ['オペレーション基盤', 'セットアップコード、インストール、リリース、アプライアンス', 'あらゆる組織内の憲法的権限'],
        ['IDプロバイダー', '外部アイデンティティそのもの', 'そのIDが何をできるかの決定'],
        ['サブストレート層', 'プロバイダー、リソース、ヘルス', '知識 — プロバイダー交換はプラクティスを変えない'],
        ['誰も所有しない', '「セレモニー完了」「実行可能」 — 各プレーンに尋ねて導出', '保存された複合状態。記録のオーケストレーターは存在しない'],
      ],
      cols: ['レイヤー', '所有するもの', '決して取り込まないもの'],
    },
    provenance: {
      eyebrow: '実行',
      h2: '説明可能な実行',
      lede: '機械が生成したすべての成果物は、何が生成し何が判断したか — モデル、プロバイダー種別、リソース、根拠 — を永続的に記録します。それは仕事に付随するエビデンスであって、ゲートではありません。リクエストが指すのはケイパビリティであって、モデルではありません。憲法へのベンダー名の混入は、スキーマが拒否します。',
      link: 'さらに深く：アーキテクチャページへ',
    },
    cta: { title: '一緒に構築する。', body: 'デザインパートナーとして参加し、実際の組織ニーズに基づくランタイムの形成にご協力ください。' },
  },
} as const satisfies Record<Locale, unknown>;

export const architecture = {
  en: {
    meta: { title: 'Architecture — Diskarte', description: 'The public architecture of the Organizational Runtime: kernel primitives, computed authority, the cognition boundary, memory planes, the epistemic pipeline, substrate abstraction, and federation.' },
    hero: { eyebrow: 'Architecture', h1: 'Boundaries first', lede: 'Diskarte’s major architectural boundaries are either enforced in implementation, established in approved doctrine, or explicitly tracked as implementation awaiting ratification. This page is the public map.' },
    concepts: [
      { h: 'Runtime anatomy', p: 'A native Desktop and an Organization Console speak to one Platform API. Behind it, a governed core: a pure kernel, orchestration, governance gates, judgment, memory, and projections — with cognition and substrate held at the edges behind ports. Deployment simplifies; architecture does not: the whole runtime can run as one local binary with every boundary intact.' },
      { h: 'Seven kernel primitives', p: 'Actor, Role, Boundary, Decision, WorkOrder, Artifact, Evaluation — and deliberately no eighth. The kernel decides all authority and never reasons, never names a substrate, and never declares completion without Evaluation.' },
      { h: 'Authority is computed', p: 'Authority(actor, context) = Role ∩ Boundary, evaluated at the moment of authorization and never stored. Three verdicts: permitted, requires-approval, forbidden. Routing is dispatch of already-authorized work — a second “who may act” concept is the failure mode the kernel refuses.' },
      { h: 'The governed spine', p: 'Boundary → Authorized Intent → WorkOrder. No governed side effect occurs except through this spine, and no work completes except through Evaluation. Authorized Intent is derived, never persisted.' },
      { h: 'Cognition reasons; it never governs', p: 'The cognition interior lives behind a single Produce/Judge port, structurally unable to touch storage, authority, identity, or lifecycle — enforced by import guards that fail the build, not by review comments. Its output is always untrusted, always attributed, and enters the organization only through the governed door.' },
      { h: 'Two memories, never conflated', p: 'Canonical memory — the set of ratified Artifacts — reconstructs the organization. Retrieval memory — embeddings and indexes — accelerates cognition and is rebuildable at any time. A vector index that becomes a source of truth is a second system of record; the split exists to prevent exactly that.' },
      { h: 'Identity is not authority', p: 'An identity provider owns one truth: this human controls this identity. Provider claims arrive as evidence and never become authority; Diskarte-owned sessions, membership, and mandates are the record — granted and revoked only by Runtime governance. Four proofs, four granters: possession, identity, legitimacy, authority.' },
      { h: 'Evidence → justified model → ratification → canon', p: 'The runtime operates on exactly two kinds of thing: observable evidence and governed commitment. Evidence is partial and never self-certifying; the justified model carries confidence and provenance; only a human ratification writes canon. The moment evidence drives governance it becomes a target — so no direct edge from evidence to canon exists.' },
      { h: 'Substrate abstraction', p: 'Practices declare abstract capability requirements. Governed bindings resolve them to providers under an organization-owned policy. Five deployment profiles — Local and Diskarte Managed adoptable today; Hybrid and Cloud architecturally defined; Air-Gapped deferred by ruling. Migration is a policy amendment, never a restart, and model identity travels only as provenance.' },
      { h: 'Operations outside authority', p: 'A separate Operations Platform provisions installations, issues setup codes, manages releases and managed appliances. Its database access is allowlisted away from every Runtime store: Diskarte-the-vendor holds no authority, read, or write inside any organization — structurally, not as policy.' },
      { h: 'Federation and artifact boundaries', p: 'The system is a federation of repositories where every cross-repo dependency is a versioned published artifact — never a source import. The Desktop is the composition point: it pins runtime and UI by digest and fails closed on mismatch. Architectural violations become build failures.' },
    ],
    doctrineText: 'Cognition reasons. It never governs.',
    doctrineSub: 'The kernel decides all authority and never reasons; cognition reasons and never decides. The seam between them is the product.',
    ctaTitle: 'Help shape the next stage.',
    ctaBody: 'Apply as a design partner to test these boundaries against real organizational needs.',
  },
  ja: {
    meta: { title: 'アーキテクチャ — Diskarte', description: '組織ランタイムの公開アーキテクチャ：カーネル・プリミティブ、計算される権限、認知境界、2つの記憶、認識のパイプライン、サブストレート抽象化、フェデレーション。' },
    hero: { eyebrow: 'アーキテクチャ', h1: '境界がすべてに先立つ', lede: 'Diskarteの主要なアーキテクチャ境界は、実装で強制されているか、承認済みドクトリンで確立されているか、あるいは「承認待ちの実装」として明示的に追跡されています。このページは公開マップです。' },
    concepts: [
      { h: 'ランタイムの解剖図', p: 'ネイティブのデスクトップと組織コンソールは、ひとつのプラットフォームAPIと対話します。その背後に統治されたコア — 純粋なカーネル、オーケストレーション、ガバナンスのゲート、判断、記憶、プロジェクション — があり、認知とサブストレートはポートの背後の端に置かれます。デプロイは単純化しても、アーキテクチャは単純化しません。全体をひとつのローカルバイナリとして、すべての境界を保ったまま実行できます。' },
      { h: '7つのカーネル・プリミティブ', p: 'Actor、Role、Boundary、Decision、WorkOrder、Artifact、Evaluation — そして意図的に8つ目はありません。カーネルはすべての権限を決定し、決して推論せず、サブストレートを名指しせず、Evaluationなしに完了を宣言しません。' },
      { h: '権限は計算される', p: 'Authority(actor, context) = Role ∩ Boundary。認可の瞬間に評価され、決して保存されません。裁定は3種類：許可・承認必要・禁止。ルーティングは「すでに認可された仕事」の配送であり、第二の「誰が行動できるか」概念はカーネルが拒否する失敗モードです。' },
      { h: '統治された背骨', p: 'Boundary → Authorized Intent → WorkOrder。統治された副作用はこの背骨を通じてのみ発生し、仕事はEvaluationを通じてのみ完了します。Authorized Intentは導出され、永続化されません。' },
      { h: '認知は推論する。決して統治しない', p: '認知のインテリアは、単一の Produce / Judge ポートの背後にあり、ストレージ・権限・アイデンティティ・ライフサイクルに構造的に触れられません — レビューコメントではなく、ビルドを失敗させるインポートガードで強制されます。その出力は常に信頼されず、常に帰属され、統治された扉からのみ組織に入ります。' },
      { h: '2つの記憶を混同しない', p: 'カノン記憶 — 承認されたArtifactの集合 — は組織を再構築します。検索記憶 — 埋め込みとインデックス — は認知を加速し、いつでも再構築可能です。真実の源になったベクトルインデックスは第二の記録システムであり、この分離はまさにそれを防ぐために存在します。' },
      { h: 'アイデンティティは権限ではない', p: 'IDプロバイダーが所有する真実はひとつ：「この人間がこのIDを制御している」。プロバイダーのクレームはエビデンスとして到着し、決して権限になりません。Diskarteが所有するセッション・メンバーシップ・マンデートが記録であり、ランタイムのガバナンスのみが付与・剥奪します。4つの証明に、4人の付与者：所持、アイデンティティ、正当性、権限。' },
      { h: 'エビデンス → 正当化されたモデル → 承認 → カノン', p: 'ランタイムが扱うのは2種類だけ：観察可能なエビデンスと、統治されたコミットメント。エビデンスは部分的で、決して自己証明しません。正当化されたモデルは確信度と来歴を持ちます。カノンを書けるのは人間の承認だけです。エビデンスが統治を動かした瞬間、それは攻略対象になる — だから、エビデンスからカノンへの直接の辺は存在しません。' },
      { h: 'サブストレート抽象化', p: 'プラクティスは抽象的なケイパビリティ要件を宣言し、統治されたバインディングが組織所有のポリシーの下でプロバイダーに解決します。5つのプロファイル — ローカルとDiskarteマネージドは今日採用可能。ハイブリッドとクラウドはアーキテクチャ確定。エアギャップはルーリングにより保留。移行はポリシー修正であって再構築ではなく、モデルの識別子は来歴としてのみ移動します。' },
      { h: '権限の外側にあるオペレーション', p: '独立したオペレーション基盤が、インストールのプロビジョニング、セットアップコードの発行、リリースとマネージド・アプライアンスの管理を行います。そのデータベースアクセスは、すべてのランタイムストアから許可リストで隔離されています。ベンダーとしてのDiskarteは、どの組織の内部でも権限・読取・書込を持ちません — ポリシーではなく、構造として。' },
      { h: 'フェデレーションとアーティファクト境界', p: 'システムはリポジトリのフェデレーションであり、リポジトリ間の依存はすべてバージョン付きの公開アーティファクトです — ソースの直接参照は決してありません。デスクトップが合成点であり、ランタイムとUIをダイジェストでピン留めし、不一致時はフェイルクローズ。アーキテクチャ違反はビルド失敗になります。' },
    ],
    doctrineText: '認知は推論する。決して統治しない。',
    doctrineSub: 'カーネルはすべての権限を決定し、決して推論しない。認知は推論し、決して決定しない。その間のシームこそがプロダクトです。',
    ctaTitle: '次のステージを共に形作る。',
    ctaBody: 'デザインパートナーとして参加し、これらの境界を実際の組織ニーズに照らして検証してください。',
  },
} as const satisfies Record<Locale, unknown>;
