import type { Locale } from '../i18n/ui';

export const home = {
  en: {
    meta: {
      title: 'Diskarte — The Organizational Runtime',
      description:
        'Diskarte gives organizations constitutional governance, memory, and judgment so they can safely delegate increasing autonomy to AI.',
    },
    hero: {
      eyebrow: 'Organizational Runtime',
      h1a: 'The Organizational',
      h1b: 'Runtime.',
      lede: 'AI made execution fast. Diskarte keeps the organization coherent — constitutional governance, memory, and judgment, so autonomy can grow safely.',
      ctaPrimary: 'Explore the Runtime',
      ctaSecondary: 'Read the Technical Overview',
    },
    problem: {
      eyebrow: 'The problem',
      h2: 'Where AI fails inside organizations',
      cards: [
        { k: '01 · Context', h: 'Tools know tasks. They do not know the organization.', p: 'AI drafts, summarizes, and executes — without knowing why the work matters, who holds authority, or which constraints cannot be violated.' },
        { k: '02 · Judgment', h: 'More output creates more undelegated judgment.', p: 'Without governed escalation, acceleration is noise — pushing more cognitive load onto exactly the person it was meant to relieve.' },
        { k: '03 · Memory', h: 'Organizations keep relearning what they already knew.', p: 'Decisions lose their rationale, projects lose context, and understanding is rebuilt every time people, tools, or priorities change.' },
      ],
      close: 'Assistants, agents, and retrieval systems each address a symptom. None owns the organization’s authority, judgment, or memory.',
    },
    missing: {
      eyebrow: 'The missing layer',
      h2: 'Between the organization and its execution machinery',
      lede: 'What is missing is not a better agent. It is constitutional authority, organizational memory, judgment, delegation, and governance — a runtime between the organization and interchangeable execution machinery.',
      law: 'Agents and models may operate inside Diskarte. They are not Diskarte. Diskarte is the runtime around them.',
    },
    product: {
      eyebrow: 'Product reality',
      h2: 'What an organization actually touches',
      lede: 'Five surfaces, honestly labeled. Statuses follow one vocabulary across everything Diskarte publishes.',
      surfaces: {
        brief: {
          title: 'The Morning Brief',
          value: 'The founder’s day starts from a synthesized brief: what needs judgment now, and what can safely wait. Every line is cited — the composer refuses ungrounded items.',
          reason: 'the scarce resource in an AI-fast organization is founder attention, so the product spends machine cycles to conserve it.',
          ui: { eyebrow: 'Morning Brief · synthesized 06:42', head: 'Two decisions need you. Four items can safely wait.', now: 'Needs you now', wait: 'Can safely wait',
            items: ['Proposal awaiting adjudication — grounded in 3 canonical artifacts', 'WorkOrder evaluation: accept or revise — dissent preserved'],
            waits: ['Fulfillment in progress — local model pulling', '2 observations entered memory overnight', 'Blind spot named: no evidence for spend approvals'] },
        },
        memory: {
          title: 'Organizational Memory',
          value: 'Memory is an epistemic state, not a filing cabinet. The organization can always answer what it observes, believes, and knows — and what it cannot yet see.',
          reason: 'a memory that cannot distinguish belief from knowledge — or name its own gaps — will eventually govern from fiction.',
          ui: { eyebrow: 'Memory · six honesty strata',
            strata: [ ['What we observe', 'evidence, with provenance'], ['What we cannot yet see', 'named blind spots, above the fold'], ['What history claims', 'reconstructed, marked as claims'], ['What we believe', 'justified, confidence-carrying'], ['What we know', 'canon — ratified by a human'], ['What we want to ask', 'ranked by information gain'] ] },
        },
        judgment: {
          title: 'Organizational Judgment',
          value: 'Two governed loops — over executed work and over candidate beliefs — both terminating in a human ruling. The interface never pre-selects a disposition; “accept all” does not exist.',
          reason: 'judgment is distinct from memory, and delegating it silently is how organizations drift.',
          ui: { eyebrow: 'Judgment · ruling required', card: 'Candidate belief: “support burden is concentrating in onboarding”', meta: 'grounded in 4 artifacts · standing: contested', actions: ['Ratify', 'Reject', 'Park with trigger'] },
        },
        practices: {
          title: 'Governed Practices',
          value: 'Adopting a capability is hiring a profession, not installing a plugin: it arrives with standards, defers to your law, and earns standing through judged work.',
          reason: 'professional knowledge should be distributable while how your organization works remains yours alone.',
          ui: { eyebrow: 'Practice · install is a ruling', steps: [ ['Capability package', 'portable knowledge · declares abstract requirements'], ['Your Practice', 'the organization’s sovereign derivation — diverges freely'], ['Precedent', 'judged work accrues; corrections decay repeats'] ] },
        },
        onboarding: {
          title: 'Greenfield onboarding',
          value: 'From a setup code to a governed organization: claim, sign in, answer a few questions, review grounded recommendations, and activate. One truth owner per step, and no step trusts another’s assertion.',
          reason: 'legitimacy, identity, and authority are three different proofs — the ceremony keeps them that way.',
          qual: 'public deployment founder-gated',
          ui: { eyebrow: 'Onboarding · profile recommendation', rec: 'Local — recommended', recSub: 'this machine can serve cognition on-device', alt: 'Diskarte Managed — viable', altSub: 'org-owned appliance, an adjudicated residency choice', gap: 'Air-Gapped — not yet available', gapSub: 'offline fulfillment awaits a deferred ruling' },
        },
      },
    },
    governance: {
      eyebrow: 'Governance enables autonomy',
      h2: 'Nothing governs until a human ratifies it',
      lede: 'Evidence is partial. Inference is contestable. Only ratified canon governs — and everything downstream of a ruling should be automated. Human judgment is spent exactly where judgment is genuinely required.',
      steps: [
        { nm: 'Evidence', ds: 'what the organization can observe — partial, sometimes stale, never self-certifying' },
        { nm: 'Justified model', ds: 'the strongest model the evidence supports — confidence-carrying, contestable' },
        { nm: 'Human ratification', ds: 'the only writer of canon and the only creator of authority', kind: 'gov' as const },
        { nm: 'Canon', ds: 'what the organization has committed to', kind: 'gov' as const },
        { nm: 'Governed action', ds: 'work executes with authority computed, completion verified, provenance recorded' },
      ],
      aria: 'Diagram: evidence becomes a justified model, which only becomes canon through human ratification; canon then drives governed action.',
      law: 'Intelligence proposes. Governance disposes. Humans remain the source of canonical authority.',
    },
    convergence: {
      eyebrow: 'Two ways in, one destination',
      h2: 'Greenfield and Brownfield converge',
      lede: 'New organizations answer questions. Existing organizations import their digital exhaust — honestly, with named blind spots. Both paths feed one advisory engine and pass through the same governed door.',
      law: 'The evidence source differs. The destination does not.',
    },
    substrate: {
      eyebrow: 'Substrate',
      h2: 'Execution without infrastructure lock-in',
      lede: 'Practices declare abstract capability requirements. Governed bindings decide what serves them. The constitution can never contain a vendor or model name — the schema refuses it.',
      law: 'Requests address capabilities, never models.',
      lawSub: 'Provider and model identity are recorded as provenance on produced work — never embedded in organizational knowledge. Replacing a provider never changes what your organization knows how to do.',
    },
    status: {
      eyebrow: 'Built and coming next',
      h2: 'Where Diskarte actually is',
      lede: 'One status vocabulary, applied everywhere. Implemented means built, committed, and proven through verification — it does not imply deployment.',
      builtHead: 'Built',
      nextHead: 'Next',
      laterHead: 'Later',
      built: [
        ['Constitutional kernel & governed work loop', 'impl'],
        ['Identity, membership & sessions', 'impl'],
        ['Morning Brief & Organizational Memory', 'impl'],
        ['Deterministic Organizational Judgment', 'impl'],
        ['Brownfield bundle import & healing', 'impl'],
        ['Desktop claim ceremony & Environment Report', 'impl'],
        ['Substrate adoption path & execution provenance', 'impl'],
        ['Managed appliance control plane', 'impl'],
        ['Internal Operations Platform', 'depl'],
      ],
      next: [
        'Founder dogfooding as Organization #1',
        'Product UX refinement & visual onboarding',
        'Public installation & distribution',
        'Production Managed deployment',
        'Hosted Runtime',
        'Broader advisory recommendations',
        'Catalog & Foundation library',
      ],
      later: ['Publisher ecosystem', 'Marketplace', 'Broader connectors', 'The organizational operating-system evolution'],
      honesty: 'Zero external organizations have used Diskarte yet, and production Managed deployment has intentionally not happened. The current focus is dogfooding, UX, distribution, and first deployments.',
    },
    overview: {
      eyebrow: 'Technical depth',
      h2: 'The complete mental model, in one document',
      title: 'The Diskarte Technical Overview',
      body: 'The complete architecture, product model, implementation status, and roadmap — 83 pages, written for engineers, with implemented and planned capabilities never conflated.',
      explore: 'Explore the Architecture',
    },
    founder: {
      eyebrow: 'Founder',
      name: 'Margaux Flores',
      role: 'Founder & Principal Engineer',
      body1: 'I spent years building software inside growing organizations — including Mercari, bitFlyer, and Tailor — modernizing production systems and shipping product as a frontend and product engineer across international, distributed teams.',
      body2: 'The technical systems kept getting faster and more capable. The organizational context around them stayed fragmented: decisions lost their rationale, authority lived in people’s heads, and every new tool created another partial view.',
      body3: 'Diskarte began as an attempt to make that missing layer explicit.',
      link: 'Read the full story',
    },
    cta: {
      title: 'Help shape the first Organizational Runtime.',
      body: 'Diskarte is entering founder dogfooding and design-partner validation. We are looking for technically serious organizations willing to test how governance, memory, and judgment should work when AI becomes part of the operating environment.',
    },
  },

  ja: {
    meta: {
      title: 'Diskarte — 組織のためのランタイム',
      description: 'Diskarteは、組織に憲法的ガバナンス・記憶・判断のレイヤーを与え、AIへの自律的な委任を安全に拡大できるようにする「組織ランタイム」です。',
    },
    hero: {
      eyebrow: 'Organizational Runtime',
      h1a: '組織のための',
      h1b: 'ランタイム。',
      lede: 'AIは実行を速くしました。Diskarteは組織の一貫性を守ります — ガバナンス・記憶・判断のレイヤーで、自律性を安全に育てるために。',
      ctaPrimary: 'ランタイムを見る',
      ctaSecondary: '技術概要を読む',
    },
    problem: {
      eyebrow: '課題',
      h2: '組織の中でAIがつまずく場所',
      cards: [
        { k: '01 · 文脈', h: 'ツールはタスクを知っていても、組織を知らない。', p: 'AIは下書きし、要約し、実行します。しかし、その仕事がなぜ重要か、誰が権限を持つか、どの制約が破れないかを知りません。' },
        { k: '02 · 判断', h: 'アウトプットが増えるほど、委任されない判断が増える。', p: '統治されたエスカレーションがなければ、加速はノイズです。負担を減らすはずだった当人に、より多くの認知負荷が戻ってきます。' },
        { k: '03 · 記憶', h: '組織は、すでに知っていたことを学び直し続ける。', p: '意思決定は根拠を失い、プロジェクトは文脈を失い、人・ツール・優先順位が変わるたびに理解が作り直されます。' },
      ],
      close: 'アシスタントも、エージェントも、検索システムも、それぞれ症状のひとつに対処するだけです。組織の権限・判断・記憶を所有するものは、どこにもありません。',
    },
    missing: {
      eyebrow: '欠けているレイヤー',
      h2: '組織と実行レイヤーのあいだに',
      lede: '欠けているのは、より優れたエージェントではありません。憲法的な権限、組織の記憶、判断、委任、ガバナンス — 組織と交換可能な実行レイヤーのあいだに立つランタイムです。',
      law: 'エージェントやモデルはDiskarteの中で動きます。しかし、それらはDiskarteではありません。Diskarteは、それらを取り囲むランタイムです。',
    },
    product: {
      eyebrow: 'プロダクトの現在地',
      h2: '組織が実際に触れるもの',
      lede: '5つのサーフェスを、正直なステータスとともに。Diskarteが公開するすべてに同じステータス語彙を使います。',
      surfaces: {
        brief: {
          title: 'モーニング・ブリーフ',
          value: '創業者の一日は、合成されたブリーフから始まります。いま判断が必要なもの、安全に待てるもの。すべての行に出典があり、根拠のない項目は合成段階で拒否されます。',
          reason: 'AI時代の組織で最も希少な資源は創業者の注意です。だから機械の計算を使って、それを節約します。',
          ui: { eyebrow: 'Morning Brief · 06:42 合成', head: '判断が必要なのは2件。4件は安全に待てます。', now: 'いま必要', wait: '安全に待てる',
            items: ['裁定待ちのプロポーザル — 3件のカノン文書に根拠', 'ワークオーダー評価：承認または差し戻し — 異論は保存されます'],
            waits: ['充足を実行中 — ローカルモデルを取得しています', '夜間に2件の観察が記憶に追加', '盲点を明示：支出承認のエビデンスなし'] },
        },
        memory: {
          title: '組織の記憶',
          value: '記憶は認識の状態であって、書類棚ではありません。観察していること、信じていること、知っていること — そして、まだ見えていないことに、組織は常に答えられます。',
          reason: '信念と知識を区別できず、自らの欠落を名指しできない記憶は、いずれ虚構から統治を始めるからです。',
          ui: { eyebrow: 'Memory · 6つの正直さの層',
            strata: [ ['観察していること', '来歴つきのエビデンス'], ['まだ見えていないこと', '名指しされた盲点を最上部に'], ['歴史が主張すること', '再構築され、主張として明示'], ['信じていること', '根拠と確信度つき'], ['知っていること', 'カノン — 人間が承認したもの'], ['尋ねたいこと', '情報利得の順に'] ] },
        },
        judgment: {
          title: '組織の判断',
          value: '実行された仕事と、候補となる信念。2つの統治されたループは、どちらも人間のルーリングで終わります。UIが処理を先に選ぶことはなく、「一括承認」は存在しません。',
          reason: '判断は記憶とは別のものであり、それを静かに委任してしまうことが、組織のドリフトの始まりだからです。',
          ui: { eyebrow: 'Judgment · ルーリングが必要', card: '候補の信念：「サポート負荷がオンボーディングに集中しつつある」', meta: '4件の文書に根拠 · スタンディング：係争中', actions: ['承認', '棄却', 'トリガー付き保留'] },
        },
        practices: {
          title: '統治されたプラクティス',
          value: 'ケイパビリティの導入は、プラグインのインストールではなく「職能を雇う」ことです。標準を携えて到着し、あなたの組織の法に従い、判断された仕事を通じて信頼を獲得します。',
          reason: '専門知識は流通可能であるべきで、同時に「あなたの組織のやり方」はあなただけのものであり続けるべきだからです。',
          ui: { eyebrow: 'Practice · インストールはルーリング', steps: [ ['ケイパビリティ・パッケージ', '可搬な知識 · 抽象的な要件を宣言'], ['あなたのプラクティス', '組織固有の主権的な派生 — 自由に分岐'], ['先例', '判断された仕事が蓄積し、繰り返しの誤りは減衰'] ] },
        },
        onboarding: {
          title: 'グリーンフィールド・オンボーディング',
          value: 'セットアップコードから、統治された組織へ。クレーム、サインイン、いくつかの質問、根拠つきの推奨のレビュー、そしてアクティベーション。各ステップに真実の所有者はひとりで、どのステップも他の主張を信用しません。',
          reason: '正当性・アイデンティティ・権限は3つの異なる証明であり、セレモニーはそれを分離されたまま保つからです。',
          qual: '公開デプロイは創業者ゲート',
          ui: { eyebrow: 'Onboarding · プロファイル推奨', rec: 'ローカル — 推奨', recSub: 'このマシンは端末内で認知を提供できます', alt: 'Diskarte マネージド — 利用可能', altSub: '組織所有のアプライアンス。裁定された選択', gap: 'エアギャップ — 現在は利用不可', gapSub: 'オフライン充足は保留中のルーリング待ち' },
        },
      },
    },
    governance: {
      eyebrow: 'ガバナンスが自律を可能にする',
      h2: '人間が承認するまで、何も統治しない',
      lede: 'エビデンスは部分的です。推論は反証可能です。統治するのは承認されたカノンだけ — そしてルーリングの下流は、すべて自動化されるべきです。人間の判断は、本当に判断が必要な場所にだけ使います。',
      steps: [
        { nm: 'エビデンス', ds: '組織が観察できるもの — 部分的で、時に古く、決して自己証明しない' },
        { nm: '正当化されたモデル', ds: 'エビデンスが支持する最良のモデル — 確信度つきで、反証可能' },
        { nm: '人間による承認', ds: 'カノンを書ける唯一の主体であり、権限を生み出せる唯一の主体', kind: 'gov' as const },
        { nm: 'カノン', ds: '組織がコミットしたこと' },
        { nm: '統治された実行', ds: '権限は計算され、完了は検証され、来歴が記録される', kind: 'gov' as const },
      ],
      aria: '図：エビデンスは正当化されたモデルになり、人間の承認を経てのみカノンとなり、カノンが統治された実行を導きます。',
      law: '知能は提案する。ガバナンスが裁く。カノンの権限の源は、常に人間である。',
    },
    convergence: {
      eyebrow: '入口はふたつ、行き先はひとつ',
      h2: 'グリーンフィールドとブラウンフィールドは収束する',
      lede: '新しい組織は質問に答えます。既存の組織はデジタルの痕跡を取り込みます — 盲点を名指しする正直さとともに。どちらの経路もひとつの推奨エンジンに合流し、同じ統治された扉を通ります。',
      law: '異なるのはエビデンスの源。行き先は変わらない。',
    },
    substrate: {
      eyebrow: 'サブストレート',
      h2: 'インフラにロックインされない実行',
      lede: 'プラクティスは抽象的なケイパビリティ要件を宣言し、統治されたバインディングが充足先を決めます。憲法にベンダー名やモデル名が入ることはありません — スキーマがそれを拒否します。',
      law: 'リクエストが指すのはケイパビリティであって、モデルではない。',
      lawSub: 'プロバイダーとモデルの識別子は、生成物の「来歴」として記録され、組織の知識には決して埋め込まれません。プロバイダーを替えても、組織が「できること」は変わりません。',
    },
    status: {
      eyebrow: '構築済みと、この先',
      h2: 'Diskarteの現在地',
      lede: 'ひとつのステータス語彙を、あらゆる場所に。「実装済み」は構築・コミット・検証済みを意味し、デプロイ済みを意味しません。',
      builtHead: '構築済み',
      nextHead: '次',
      laterHead: 'その先',
      built: [
        ['憲法的カーネルと統治されたワークループ', 'impl'],
        ['アイデンティティ・メンバーシップ・セッション', 'impl'],
        ['モーニング・ブリーフと組織の記憶', 'impl'],
        ['決定論的な組織の判断', 'impl'],
        ['ブラウンフィールド取込と修復', 'impl'],
        ['デスクトップのクレーム・セレモニーと環境レポート', 'impl'],
        ['サブストレート採用パスと実行来歴', 'impl'],
        ['マネージド・アプライアンス制御プレーン', 'impl'],
        ['社内オペレーション基盤', 'depl'],
      ],
      next: [
        '創業者による本格的なドッグフーディング（組織 #1）',
        'プロダクトUXの磨き込みとビジュアル・オンボーディング',
        '公開インストールと配布',
        'マネージドの本番デプロイ',
        'ホステッド・ランタイム',
        'アドバイザリー推奨の拡張',
        'カタログとファウンデーション・ライブラリ',
      ],
      later: ['パブリッシャー・エコシステム', 'マーケットプレイス', 'コネクターの拡充', '「組織のOS」への進化'],
      honesty: '外部組織による利用はまだゼロであり、マネージドの本番デプロイは意図的に行っていません。現在の焦点は、ドッグフーディング、UX、配布、そして最初のデプロイです。',
    },
    overview: {
      eyebrow: '技術的な深さ',
      h2: '完全なメンタルモデルを、1つのドキュメントで',
      title: 'Diskarte 技術概要',
      body: 'アーキテクチャ、プロダクトモデル、実装ステータス、ロードマップの全体像 — 全83ページ。エンジニアのために書かれ、実装済みと計画中を決して混同しません。（本文は英語です）',
      explore: 'アーキテクチャを見る',
    },
    founder: {
      eyebrow: '創業者',
      name: 'Margaux Flores（マルゴ・フロレス）',
      role: '創業者 & プリンシパルエンジニア',
      body1: '私は成長する組織の中でソフトウェアを作り続けてきました — メルカリ、bitFlyer、Tailorなどで、本番システムのモダナイゼーションと、国際的な分散チームでのフロントエンド／プロダクト開発に携わってきました。',
      body2: '技術システムは速く、有能になり続けました。しかしその周囲の組織的文脈は、断片化したままでした。意思決定は根拠を失い、権限は人の頭の中にあり、新しいツールはまた別の部分的なビューを生み出しました。',
      body3: 'Diskarteは、その「欠けているレイヤー」を明示的なものにする試みとして始まりました。',
      link: 'ストーリー全文を読む',
    },
    cta: {
      title: '最初の「組織ランタイム」を、一緒に形にしませんか。',
      body: 'Diskarteは、創業者によるドッグフーディングとデザインパートナー検証の段階に入ります。AIが業務環境の一部になるとき、ガバナンス・記憶・判断はどうあるべきか — それを本気で検証してくださる、技術的に真剣な組織を探しています。',
    },
  },
} as const satisfies Record<Locale, unknown>;
